
// kernel physical memory
#define PMEM_KERN_START (0xF000)
#define PMEM_KERN_SIZE (200 * 1024 * 1024)

// user physical memory
#define PMEM_USR_START (PMEM_KERN_START + PMEM_KERN_SIZE)

#define MAX_ALLOCATION_POWER 11
#define MIN_ALLOCATION_POWER 2
#define MAX_ALLOCATION_SIZE (2 ^ MAX_ALLOCATION_POWER * 1024)
#define MIN_ALLOCATION_SIZE (2 ^ MIN_ALLOCATION_POWER * 1024)
#define HEAP_SIZE (MAX_ALLOCATION_SIZE * 2)
#define MAX_NUMBER_OF_BLOCKS (HEAP_SIZE / MIN_ALLOCATION_SIZE)
#define NUMBER_OF_ALLOCATION_SIZES (MAX_ALLOCATION_POWER - MIN_ALLOCATION_POWER + 1)
#define MIN_NUMBER_OF_BLOCKS 2
#define BLOCK_INCREASE_BY_DIV 2
// geometric series to determine the number of bits needed for all allocation sizes
#define BUDDY_BIT_MAP_WIDTH (MIN_NUMBER_OF_BLOCKS * ((1 - BLOCK_INCREASE_BY_DIV ^ NUMBER_OF_ALLOCATION_SIZES) / (1 - BLOCK_INCREASE_BY_DIV)))
#define HEAP_END_ADDRESS (HEAP_SIZE + HEAP_START_ADDRESS)
